using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
namespace Banking.Data.Models;

public class Account
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Automatically generated by the database
    public int AccountNumber { get; set; }

    [Range(0, double.MaxValue, ErrorMessage = "Balance cannot be negative.")]
    public decimal Balance { get; set; }

    public bool IsDeleted { get; set; } = false;

    public int ClientId { get; set; }

    public Client Client { get; set; }
}
